query threads {
  threads {
    id
    name
    user {
      id
      email
      role {
        id
        description
      }
    }
    Image {
      id
      url
    }
    created_at
    posts {
      id
      title
      content
      tags
      like_count
      created_at
    	user {
        username
        email
        id
      }
      comments {
        content
        user {
          username
          email
          id
        }
        updated_at
      }
    }
    admin_accepted
  }
}
