# Write your query or mutation here
query thread_posts($id: ID!) {
  thread(id: $id) {
    id
    name
    user {
      id
      username
      email
      role {
        id
        description
      }
    }
    Image {
      id
      url
    }
    created_at
    posts {
      id
      title
    	content
      tags
      like_count
      comments {
        id
        content
        user {
          username
          email
          id
        }
        created_at
        updated_at
      }
      user {
        id
        username
      }
    }
    updated_at
    admin_accepted
  }
}
