# Write your query or mutation here
query threads {
  threads {
    id
    name
    user {
      id
      email
      role {
        id
        description
      }
    }
    Image {
      id
      url
    }
    created_at
    posts {
      title
      content
      user {
        username
        email
        id
      }
      like_count
      comments {
        content
        user {
          username
          email
          id
        }
        id
        created_at
        updated_at
      }
    }
    admin_accepted
  }
}
