query post($id: ID!) {
  post(id: $id) {
    id
    title
    content
    created_at
    like_count
    tags {
      id
      tag_name
    }
    comments {
      id
      content
      user {
        id
        username
      }
      created_at
      updated_at
    }
    user {
      id
      username
      email
      role {
        id
        name
      }
    }
  }
}
