query posts {
  posts {
    id
    title
    content
    tags
    like_count
    created_at
    comments {
      id
      content
      user {
        id
        username
      }
      created_at
      updated_at
    }
    user {
      id
      username
      email
      role {
        id
        name
      }
    }
  }
}
