query Posts {
  posts {
    id
    title
    content
    created_at
    category {
      name
    }
    tags {
      tag_name
    }
    comments {
      content
      like_count
      user {
        username
      }
      id
      created_at
      updated_at
    }
  }
}
